name: Release
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install  --immutable
    - run: yarn tsc
    - run: yarn build
#    - run: yarn coverage
#    - name: Publish to coveralls.io
#      uses: coverallsapp/github-action@v1.1.2
#      with:
#        github-token: ${{ secrets.GITHUB_TOKEN }}
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
      - run: git pull
      - run: yarn
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - run: yarn bump
      - run: git push --follow-tags
  tagged-release:
      name: Create tagged release
      needs: [ bump-version ]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - run: git pull
        - name: 'Get Previous tag'
          id: previoustag
          uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        - uses: marvinpinto/action-automatic-releases@latest
          with:
            repo_token: '${{ secrets.GITHUB_TOKEN }}'
            prerelease: false
            automatic_release_tag: ${{ steps.previoustag.outputs.tag }}
            files: 'CHANGELOG.md'
  frontend-publish:
    name: Publish plugin frontend
    runs-on: ubuntu-latest
    needs: [tagged-release]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          always-auth: true
          registry-url: 'https://registry.npmjs.org'
      - run: git pull
      - run: yarn
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

